GET http://localhost:3001/ipasibas

###

GET http://localhost:3001/pasutijumi/2

###

POST http://localhost:3001/pasutijumi
Content-Type: application/json

{
    "id_lietotaji": "1",
    "status": "Gaida apmaksu",
    "izveidosanas_datums": "2030-04-09 15:14:00"
}

###

DELETE http://localhost:3001/pasutijumi/14

###

PATCH http://localhost:3001/pasutijumi/14
Content-Type: application/json

{
    "status": "Izpildīts",
    "izveidosanas_datums": "2050-04-09 15:14:00"
}